# Default DQN configuration for Ms. Pac-Man
default_dqn:
  name: "default"
  note: "baseline"

  # Network parameters
  learning_rate: 0.0001

  # Memory parameters
  buffer_size: 100000
  batch_size: 32

  # Training parameters
  num_episodes: 50000
  gamma: 0.99
  target_update_freq: 1000

  # Exploration parameters
  initial_epsilon: 1.0
  final_epsilon: 0.01
  epsilon_decay_episodes: 20000

  # Logging parameters
  moving_avg_window: 100
