# Default DQN configuration for Ms. Pac-Man
default_dqn_1:
  name: "default"
  note: "baseline"

  # Network parameters
  learning_rate: 0.0001
  optimizer: "adam"  # Added optimizer parameter

  # Memory parameters
  buffer_type: "prioritized_buff"  # Added buffer type
  buffer_size: 100000
  batch_size: 64  # Updated batch size

  # Training parameters
  num_episodes: 50000
  gamma: 0.99
  target_update_freq: 10000  # Updated target update frequency

  # Exploration parameters
  initial_epsilon: 1.0
  epsilon_min: 0.1
  decay_rate: 70000  # Updated decay rate
  epsilon_decay: 0.999


  # Logging parameters
  moving_avg_window: 100
  log_dir: "logs/default_dqn_1"  # Added log directory

  dqn_type: "double dueling dqn"  # Added DQN type

  model_path: "models/default_dqn_1.pth"  # Added model path

  train_dqn: True
  test_dqn: False

default_double_dqn_1:
  name: "default"
  note: "baseline"

  # Network parameters
  learning_rate: 0.0001
  optimizer: "adam"  # Added optimizer parameter

  # Memory parameters
  buffer_type: "std_buff"  # Added buffer type
  buffer_size: 100000
  batch_size: 64  # Updated batch size

  # Training parameters
  num_episodes: 500000
  gamma: 0.99
  target_update_freq: 10000  # Updated target update frequency

  # Exploration parameters
  initial_epsilon: 1.0
  epsilon_min: 0.01
  decay_rate: 70000  # Updated decay rate
  epsilon_decay: 0.999


  # Logging parameters
  moving_avg_window: 100
  log_dir: "logs/default_double_dqn_1"  # Added log directory

  dqn_type: "double dqn"  # Added DQN type

  model_path: "models/default_double_dqn_1.pth"  # Added model path

  train_dqn: True
  test_dqn: False
  record_video: False

default_double_dqn_2:
  name: "batch_size_128"
  note: "Killed Increased batch size for better gradient estimation"

  learning_rate: 0.0001
  optimizer: "adam"

  buffer_type: "std_buff"
  buffer_size: 100000
  batch_size: 128  # Increased batch size

  num_episodes: 500000
  gamma: 0.99
  target_update_freq: 10000

  initial_epsilon: 1.0
  epsilon_min: 0.01
  decay_rate: 70000
  epsilon_decay: 0.999

  moving_avg_window: 100
  log_dir: "logs/default_double_dqn_2"
  dqn_type: "double dqn"
  model_path: "models/default_double_dqn_2.pth"
  train_dqn: True
  test_dqn: False
  record_video: False

default_double_dqn_3:
  name: "batch_size_32"
  note: "Decreased batch size for faster updates"

  learning_rate: 0.0001
  optimizer: "adam"

  buffer_type: "std_buff"
  buffer_size: 100000
  batch_size: 32  # Decreased batch size

  num_episodes: 500000
  gamma: 0.99
  target_update_freq: 10000

  initial_epsilon: 1.0
  epsilon_min: 0.01
  decay_rate: 70000
  epsilon_decay: 0.999

  moving_avg_window: 100
  log_dir: "logs/default_double_dqn_3"
  dqn_type: "double dqn"
  model_path: "models/default_double_dqn_3.pth"
  train_dqn: True
  test_dqn: False
  record_video: False

default_double_dqn_4:
  name: "fast_epsilon_decay"
  note: "Killed Faster epsilon decay for aggressive exploitation"

  learning_rate: 0.0001
  optimizer: "adam"

  buffer_type: "std_buff"
  buffer_size: 100000
  batch_size: 64

  num_episodes: 50000
  gamma: 0.99
  target_update_freq: 10000

  initial_epsilon: 1.0
  epsilon_min: 0.01
  decay_rate: 50000  # Faster decay rate
  epsilon_decay: 0.995  # Slightly faster epsilon decay

  moving_avg_window: 100
  log_dir: "logs/default_double_dqn_4"
  dqn_type: "double dqn"
  model_path: "models/default_double_dqn_4.pth"
  train_dqn: True
  test_dqn: False
  record_video: False

default_double_dqn_5:
  name: "slow_epsilon_decay"
  note: "Slower epsilon decay for more exploration"

  learning_rate: 0.0001
  optimizer: "adam"

  buffer_type: "std_buff"
  buffer_size: 100000
  batch_size: 64

  num_episodes: 500000
  gamma: 0.99
  target_update_freq: 10000

  initial_epsilon: 1.0
  epsilon_min: 0.01
  decay_rate: 100000  # Slower decay rate
  epsilon_decay: 0.9999  # Slower epsilon decay

  moving_avg_window: 100
  log_dir: "logs/default_double_dqn_5"
  dqn_type: "double dqn"
  model_path: "models/default_double_dqn_5.pth"
  train_dqn: True
  test_dqn: False
  record_video: False

default_double_dqn_6:
  name: "rmsprop_optimizer"
  note: "Switched to RMSProp optimizer"

  learning_rate: 0.0001
  optimizer: "rmsprop"  # Changed optimizer

  buffer_type: "std_buff"
  buffer_size: 100000
  batch_size: 64

  num_episodes: 500000
  gamma: 0.99
  target_update_freq: 10000

  initial_epsilon: 1.0
  epsilon_min: 0.01
  decay_rate: 70000
  epsilon_decay: 0.999

  moving_avg_window: 100
  log_dir: "logs/default_double_dqn_6"
  dqn_type: "double dqn"
  model_path: "models/default_double_dqn_6.pth"
  train_dqn: True
  test_dqn: False
  record_video: False

default_double_dqn_7:
  name: "increased_lr"
  note: "Increased learning rate for faster convergence"

  learning_rate: 0.001  # Increased learning rate
  optimizer: "adam"

  buffer_type: "std_buff"
  buffer_size: 100000
  batch_size: 64

  num_episodes: 500000
  gamma: 0.99
  target_update_freq: 10000

  initial_epsilon: 1.0
  epsilon_min: 0.01
  decay_rate: 70000
  epsilon_decay: 0.999

  moving_avg_window: 100
  log_dir: "logs/default_double_dqn_7"
  dqn_type: "double dqn"
  model_path: "models/default_double_dqn_7.pth"
  train_dqn: True
  test_dqn: False
  record_video: False

default_double_dqn_8:
  name: "decreased_lr"
  note: "Decreased learning rate for stability"

  learning_rate: 0.00005  # Decreased learning rate
  optimizer: "adam"

  buffer_type: "std_buff"
  buffer_size: 100000
  batch_size: 64

  num_episodes: 500000
  gamma: 0.99
  target_update_freq: 10000

  initial_epsilon: 1.0
  epsilon_min: 0.01
  decay_rate: 70000
  epsilon_decay: 0.999

  moving_avg_window: 100
  log_dir: "logs/default_double_dqn_8"
  dqn_type: "double dqn"
  model_path: "models/default_double_dqn_8.pth"
  train_dqn: True
  test_dqn: False
  record_video: False

default_double_dqn_9:
  name: "reduced_buffer"
  note: "Reduced buffer size for faster memory updates"

  learning_rate: 0.0001
  optimizer: "adam"

  buffer_type: "std_buff"
  buffer_size: 50000  # Reduced buffer size
  batch_size: 64

  num_episodes: 500000
  gamma: 0.99
  target_update_freq: 10000

  initial_epsilon: 1.0
  epsilon_min: 0.01
  decay_rate: 70000
  epsilon_decay: 0.999

  moving_avg_window: 100
  log_dir: "logs/default_double_dqn_9"
  dqn_type: "double dqn"
  model_path: "models/default_double_dqn_9.pth"
  train_dqn: True
  test_dqn: False
  record_video: False

default_double_dqn_10:
  name: "prioritized_replay"
  note: "Switched to prioritized replay buffer"

  learning_rate: 0.0001
  optimizer: "adam"

  buffer_type: "prioritized_buff"  # Changed buffer type
  buffer_size: 100000
  batch_size: 64

  num_episodes: 500000
  gamma: 0.99
  target_update_freq: 10000

  initial_epsilon: 1.0
  epsilon_min: 0.01
  decay_rate: 70000
  epsilon_decay: 0.999

  moving_avg_window: 100
  log_dir: "logs/default_double_dqn_10"
  dqn_type: "double dqn"
  model_path: "models/default_double_dqn_10.pth"
  train_dqn: True
  test_dqn: False
  record_video: False

# Test Low Learning Rate 
low_lr: 
  name: "default"
  note: "low_lr"

  # Network parameters
  learning_rate: 0.00001
  optimizer: "rmsprop"  # Added optimizer parameter

  # Memory parameters
  buffer_type: "std_buff"  # Added buffer type
  buffer_size: 100000
  batch_size: 64  # Updated batch size

  # Training parameters
  num_episodes: 70000
  gamma: 0.99
  target_update_freq: 10000  # Updated target update frequency

  # Exploration parameters
  initial_epsilon: 1.0
  epsilon_min: 0.1
  decay_rate: 70000  # Updated decay rate
  epsilon_decay: 0.999


  # Logging parameters
  moving_avg_window: 100
  log_dir: "logs/test_lr_0_00001"  # Added log directory

  dqn_type: "double dueling dqn"  # Added DQN type

  model_path: "models/test_low_lr.pth"  # Added model path

  train_dqn: True
  test_dqn: False

# Test Moderate Learning Rate 
moderate_lr: 
  name: "default"
  note: "mod_lr"

  # Network parameters
  learning_rate: 0.0001
  optimizer: "rmsprop"  # Added optimizer parameter

  # Memory parameters
  buffer_type: "std_buff"  # Added buffer type
  buffer_size: 100000
  batch_size: 64  # Updated batch size

  # Training parameters
  num_episodes: 70000
  gamma: 0.99
  target_update_freq: 10000  # Updated target update frequency

  # Exploration parameters
  initial_epsilon: 1.0
  epsilon_min: 0.1
  decay_rate: 70000  # Updated decay rate
  epsilon_decay: 0.999


  # Logging parameters
  moving_avg_window: 100
  log_dir: "logs/test_lr_0_0001"  # Added log directory

  dqn_type: "double dueling dqn"  # Added DQN type

  model_path: "models/test_mod_lr.pth"  # Added model path

  train_dqn: True
  test_dqn: False
  
# Test High Learning Rate
high_lr: 
  name: "default"
  note: "high_lr"

  # Network parameters
  learning_rate: 0.001
  optimizer: "rmsprop"  # Added optimizer parameter

  # Memory parameters
  buffer_type: "std_buff"  # Added buffer type
  buffer_size: 100000
  batch_size: 64  # Updated batch size

  # Training parameters
  num_episodes: 70000
  gamma: 0.99
  target_update_freq: 10000  # Updated target update frequency

  # Exploration parameters
  initial_epsilon: 1.0
  epsilon_min: 0.1
  decay_rate: 70000  # Updated decay rate
  epsilon_decay: 0.999


  # Logging parameters
  moving_avg_window: 100
  log_dir: "logs/test_lr_0_001"  # Added log directory

  dqn_type: "double dueling dqn"  # Added DQN type

  model_path: "models/test_high_lr.pth"  # Added model path

  train_dqn: True
  test_dqn: False

# Test Larger batch size 
batch_128: 
  name: "default"
  note: "batch_128"

  # Network parameters
  learning_rate: 0.0001
  optimizer: "rmsprop"  # Added optimizer parameter

  # Memory parameters
  buffer_type: "std_buff"  # Added buffer type
  buffer_size: 100000
  batch_size: 128  # Updated batch size

  # Training parameters
  num_episodes: 70000
  gamma: 0.99
  target_update_freq: 10000  # Updated target update frequency

  # Exploration parameters
  initial_epsilon: 1.0
  epsilon_min: 0.1
  decay_rate: 70000  # Updated decay rate
  epsilon_decay: 0.999


  # Logging parameters
  moving_avg_window: 100
  log_dir: "logs/test_batch_128"  # Added log directory

  dqn_type: "double dueling dqn"  # Added DQN type

  model_path: "models/test_batch_128.pth"  # Added model path

  train_dqn: True
  test_dqn: False

# Test target update frequency 
# Test Low Frequency 
low_freq: 
  name: "default"
  note: "low_freq"

  # Network parameters
  learning_rate: 0.0001
  optimizer: "rmsprop"  # Added optimizer parameter

  # Memory parameters
  buffer_type: "std_buff"  # Added buffer type
  buffer_size: 100000
  batch_size: 64  # Updated batch size

  # Training parameters
  num_episodes: 70000
  gamma: 0.99
  target_update_freq: 5000  # Updated target update frequency

  # Exploration parameters
  initial_epsilon: 1.0
  epsilon_min: 0.1
  decay_rate: 70000  # Updated decay rate
  epsilon_decay: 0.999


  # Logging parameters
  moving_avg_window: 100
  log_dir: "logs/test_low_freq"  # Added log directory

  dqn_type: "double dueling dqn"  # Added DQN type

  model_path: "models/test_low_freq.pth"  # Added model path

  train_dqn: True
  test_dqn: False

# Test high Frequency 
high_freq: 
  name: "default"
  note: "high_freq"

  # Network parameters
  learning_rate: 0.0001
  optimizer: "rmsprop"  # Added optimizer parameter

  # Memory parameters
  buffer_type: "std_buff"  # Added buffer type
  buffer_size: 100000
  batch_size: 64  # Updated batch size

  # Training parameters
  num_episodes: 70000
  gamma: 0.99
  target_update_freq: 20000  # Updated target update frequency

  # Exploration parameters
  initial_epsilon: 1.0
  epsilon_min: 0.1
  decay_rate: 70000  # Updated decay rate
  epsilon_decay: 0.999


  # Logging parameters
  moving_avg_window: 100
  log_dir: "logs/test_high_freq"  # Added log directory

  dqn_type: "double dueling dqn"  # Added DQN type

  model_path: "models/test_high_freq.pth"  # Added model path

  train_dqn: True
  test_dqn: False

# Test Different Final Epsilon 
# Low Final Epsilon 
low_epsilon: 
  name: "default"
  note: "low_epsilon"

  # Network parameters
  learning_rate: 0.0001
  optimizer: "rmsprop"  # Added optimizer parameter

  # Memory parameters
  buffer_type: "std_buff"  # Added buffer type
  buffer_size: 100000
  batch_size: 64  # Updated batch size

  # Training parameters
  num_episodes: 70000
  gamma: 0.99
  target_update_freq: 10000  # Updated target update frequency

  # Exploration parameters
  initial_epsilon: 1.0
  epsilon_min: 0.01
  decay_rate: 70000  # Updated decay rate
  epsilon_decay: 0.999


  # Logging parameters
  moving_avg_window: 100
  log_dir: "logs/test_low_epsilon"  # Added log directory

  dqn_type: "double dueling dqn"  # Added DQN type

  model_path: "models/test_low_epsilon.pth"  # Added model path

  train_dqn: True
  test_dqn: False

# High Final Epsilon 
high_epsilon: 
  name: "default"
  note: "high_epsilon"

  # Network parameters
  learning_rate: 0.0001
  optimizer: "rmsprop"  # Added optimizer parameter

  # Memory parameters
  buffer_type: "std_buff"  # Added buffer type
  buffer_size: 100000
  batch_size: 64  # Updated batch size

  # Training parameters
  num_episodes: 70000
  gamma: 0.99
  target_update_freq: 10000  # Updated target update frequency

  # Exploration parameters
  initial_epsilon: 1.0
  epsilon_min: 0.2
  decay_rate: 70000  # Updated decay rate
  epsilon_decay: 0.999


  # Logging parameters
  moving_avg_window: 100
  log_dir: "logs/test_high_epsilon"  # Added log directory

  dqn_type: "double dueling dqn"  # Added DQN type

  model_path: "models/test_high_epsilon.pth"  # Added model path

  train_dqn: True
  test_dqn: False
